### ISSUE TITLE
Error URLs

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-platform-js#2]
Inspiration: https://rauchg.com/2016/addressable-errors

Suggested implementation:

* Change log lines to accept an errCode param
* Change console.warn to console.warn(message + ". Find help at https://github.com/pusher/pusher-platform-js/wiki/errors/" + errCode)
* Change log calls to e.g. `Logger.warn("AUTH_RESPONSE_NOT_JSON", ...);`
* Then the error lives at https://github.com/pusher/pusher-platform-js/wiki/errors/AUTH_RESPONSE_NOT_JSON
* We may wish to put a proxy in the middle for nicer handling of non-existent error pages, e.g. `https://errors.pusher.com/pusher-platform-js/AUTH_RESPONSE_NOT_JSON` redirects to the above page

**Comment by hamchapman** [comment]
Done in #80
