### ISSUE TITLE
Polyfill promises

### ISSUE THREAD

**Issue by hph** [pusher/pusher-platform-js#37]
### What, why and how?

Since this library relies on `Promise`, we must ensure it's available. [This](https://github.com/stefanpenner/es6-promise) is probably the best option. The dashboard is using it [like this](https://github.com/pusher/elements-dashboard/blob/master/config/webpack.config.js#L79-L80). Let me know if I can be of any assistance.

----

CC @pusher/sigsdk

**Comment by hamchapman** [comment]
Closing as I don't think we need to do this. Might still be worth adding something to the README but we'll see.

**Comment by hph** [comment]
@zmarkan & @hamchapman I think we don't need to and shouldn't include a Promise polyfill, but we should make it very clear that one is required in order to support IE11 and other older browsers. Generally "modern" apps make use of Promises and most apps should already include a polyfill if legacy browser support is important.
