### ISSUE TITLE
Non-resumable subscriptions aren’t as polished as resumable

### ISSUE THREAD

**Issue by hot-leaf-juice** [pusher/pusher-platform-js#53]
### What?

Non-resumable subscriptions don’t reconnect, and they still fire this “state change error” on page refresh. If they behaved the same as resumable subscriptions that would be great!

#### Why?

Consistency.

#### How?

Similar reconnection strategy? And whatever you did to resumable subscriptions to suppress that page refresh error 🙂

----

CC @pusher/sigsdk

**Comment by hamchapman** [comment]
AFAIK this is fixed.
