### ISSUE TITLE
Elements clients should only retry after 5xx reponses

### ISSUE THREAD

**Issue by turingincomplete** [pusher/pusher-platform-js#55]
### What?
Elements clients should not retry a subscription request unless the Retry-After header is present AND the error response is in the 5xx range.
...

#### Why?
See the spec: https://elements-manual.pusher.com/protocol/http-sub.html#retry-after-headers
...

#### How?
Whack another condition in retry-strategy.ts: isRetryable I guess!
...

----

CC @pusher/sigsdk

**Comment by hamchapman** [comment]
Looks like this is the case now: https://github.com/pusher/pusher-platform-js/blob/master/src/retry-strategy.ts#L113

Closing but please tell me if I've misunderstood and we need to reopen.
